INSERT INTO users VALUES(DEFAULT, 'wps', 'f0e272b0741e2a259fc10111a65445608294fdbf894a11ca1652bbfdef121ffbc7aecfa0b475a743', 'ROLE_ADMIN');
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.JTSConvexHullAlgorithm','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.DummyTestClass','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.LongRunningDummyTestClass','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.MultipleComplexInAndOutputsDummyTestClass','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.MultiReferenceInputAlgorithm','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.MultiReferenceBinaryInputAlgorithm','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.EchoProcess','org.n52.wps.server.LocalAlgorithmRepositoryConfigurationModule',TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', '', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.datahandler.parser.GenericFileParserConfigurationModule',TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', '', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.modules.GenericFileDataWithGTGeneratorCM',TRUE);

DELETE FROM CONFIGURATIONMODULE WHERE MODULE_CLASS_NAME='org.n52.wps.server.database.PostgresDatabaseConfigurationModule';
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.server.database.PostgresDatabaseConfigurationModule',FALSE);
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.webapp.entities.Server',TRUE);
INSERT INTO CONFIGURATIONENTRY VALUES('hostport','org.n52.wps.webapp.entities.Server','8080');