INSERT INTO users VALUES(DEFAULT, 'wps', 'f0e272b0741e2a259fc10111a65445608294fdbf894a11ca1652bbfdef121ffbc7aecfa0b475a743', 'ROLE_ADMIN');
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.JTSConvexHullAlgorithm','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.DummyTestClass','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.LongRunningDummyTestClass','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.MultipleComplexInAndOutputsDummyTestClass','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.MultiReferenceInputAlgorithm','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.MultiReferenceBinaryInputAlgorithm','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('org.n52.wps.server.algorithm.test.EchoProcess','org.n52.wps.server.modules.LocalAlgorithmRepositoryCM',TRUE);

INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM', FALSE);

INSERT INTO ALGORITHMENTRY VALUES('i.atcorr','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.biomass','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.cca','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.cluster','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.eb.eta','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.eb.evapfr','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.eb.h_SEBAL01','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.eb.soilheatflux','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.emissivity','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.evapo.time_integration','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.fft','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.gensig','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.gensigset','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.his.rgb','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.ifft','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.landsat.acca','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.landsat.toar','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.latlong','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.maxlik','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.modis.qc','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.pca','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.rectify','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.rgb.his','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.smap','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.sunhours','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.target','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.vi','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('i.zc','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('m.cogo','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('m.measure','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.basins.fill','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.bitpattern','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.buffer2','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.carve','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.category','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.circle','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.clump','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.coin','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.compress','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.contour','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.cost','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.covar','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.cross','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.describe','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.distance','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.drain','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.fill.dir','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.flow','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.grow.distance','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.gwflow','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.his','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.horizon','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.kappa','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.lake','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.cwed','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.dominance','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.edgedensity','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.mpa','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.mps','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.padcv','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.padrange','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.padsd','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.patchdensity','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.patchnum','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.richness','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.shannon','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.shape','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.li.simpson','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.los','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.mapcalc','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.mfilter','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.mode','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.neighbors','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.null','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.param.scale','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.patch','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.profile','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.proj','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.quant','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.quantile','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.random.cells','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.random','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.random.surface','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.reclass','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.recode','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.region','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.regression.line','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.report','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.resamp.bspline','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.resamp.filter','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.resamp.interp','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.resamp.rst','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.resamp.stats','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.resample','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.rescale.eq','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.rescale','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.ros','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.series','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.sim.sediment','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.sim.water','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.slope.aspect','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.solute.transport','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.spread','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.spreadpath','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.statistics','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.statistics2','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.statistics3','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.stats','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.sun','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.sunmask','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.support','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.support.stats','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.area','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.contour','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.fractal','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.gauss','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.idw','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.idw2','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.surf.random','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.terraflow','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.texture','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.thin','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.timestamp','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.to.rast3','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.to.rast3elev','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.to.vect','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.topidx','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.topmodel','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.transect','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.univar','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.uslek','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.usler','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.volume','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.walk','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.water.outlet','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r.watershed','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.gwflow','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.info','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.mapcalc','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.mask','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.null','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.stats','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.timestamp','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.to.rast','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('r3.univar','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.buffer','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.build','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.build.polylines','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.category','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.class','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.convert','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.db.connect','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.db.select','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.delaunay','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.distance','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.drape','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.edit','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.extract','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.extrude','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.generalize','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.hull','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.kcv','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.kernel','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.label','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lidar.correction','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lidar.edgedetection','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lidar.growing','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lrs.create','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lrs.label','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lrs.segment','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.lrs.where','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.mkgrid','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.neighbors','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.alloc','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.allpairs','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.bridge','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.centrality','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.components','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.connectivity','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.distance','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.flow','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.iso','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.path','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.salesman','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.spanningtree','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.steiner','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.timetable','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.net.visibility','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.normal','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.outlier','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.overlay','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.parallel','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.patch','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.perturb','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.proj','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.qcount','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.random','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.reclass','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.sample','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.segment','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.select','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.split','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.support','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.surf.bspline','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.surf.idw','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.surf.rst','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.to.3d','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.to.db','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.to.points','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.to.rast','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.to.rast3','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.transform','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.type','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.univar','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.vol.rst','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);
INSERT INTO ALGORITHMENTRY VALUES('v.voronoi','org.n52.wps.server.grass.configurationmodule.GrassProcessRepositoryCM',TRUE);

INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.server.sextante.configurationmodule.SextanteProcessRepositoryCM', FALSE);

INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.io.modules.generator.GeoserverWMSGeneratorCM', FALSE);
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.io.modules.generator.GeoserverWFSGeneratorCM', FALSE);
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.io.modules.generator.GeoserverWCSGeneratorCM', FALSE);
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.io.modules.generator.MapserverWMSGeneratorCM', FALSE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', '', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileParserCM',TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', '', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.modules.parser.GenericFileDataWithGTParserCM',TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', '', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileGeneratorCM',TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', '', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+Spatial', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPoints', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/rData+SpatialPolygons', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.modules.generator.GenericFileDataWithGTGeneratorCM',TRUE);

INSERT INTO FORMATENTRY VALUES('application/wkt', '', '', 'org.n52.wps.io.modules.parser.WKTParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/wkt', '', '', 'org.n52.wps.io.modules.generator.WKTGeneratorCM',TRUE);

INSERT INTO FORMATENTRY VALUES('application/vnd.geo+json', '', '', 'org.n52.wps.io.modules.parser.GeoJSONParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('application/vnd.geo+json', '', '', 'org.n52.wps.io.modules.generator.GeoJSONGeneratorCM',TRUE);

INSERT INTO FORMATENTRY VALUES('text/plain', 'http://schemas.opengis.net/wcps/1.0/wcpsAll.xsd', '', 'org.n52.wps.io.modules.parser.WCPSQueryParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', 'http://schemas.opengis.net/wcps/1.0/wcpsAll.xsd', '', 'org.n52.wps.io.modules.generator.WCPSGeneratorCM',TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', '', '', 'org.n52.wps.io.modules.parser.GenericXMLDataParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.parser.GenericXMLDataParserCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', '', '', 'org.n52.wps.io.modules.generator.GenericXMLDataGeneratorCM',TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.generator.GenericXMLDataGeneratorCM',TRUE);

INSERT INTO FORMATENTRY VALUES('application/img', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', 'base64', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/img', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE); 
INSERT INTO FORMATENTRY VALUES('image/geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/dbase', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/remap', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-erdas-hfa', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-netcdf', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/dgn', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/jpeg', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/png', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-geotiff', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/hdf4-eos', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/plain', '', '', 'org.n52.wps.io.modules.parser.GenericRasterFileParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.parser.GeotiffParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GeotiffParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.parser.GeotiffParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/geotiff', '', '', 'org.n52.wps.io.modules.parser.GeotiffParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('image/x-zipped-tiff', '', 'base64', 'org.n52.wps.io.modules.parser.GeotiffZippedParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/x-zipped-geotiff', '', 'base64', 'org.n52.wps.io.modules.parser.GeotiffZippedParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/x-zipped-tiff', '', '', 'org.n52.wps.io.modules.parser.GeotiffZippedParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/x-zipped-geotiff', '', '', 'org.n52.wps.io.modules.parser.GeotiffZippedParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.0', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.1', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.0', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.1', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.2.1', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParser4FilesCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.0.0', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.1', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2.1', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParser4FilesCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.0', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.1', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.0', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.1', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML3BasicParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML32BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.2.1', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML32BasicParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://www.opengeospatial.org/gmlpacket.xsd', '', 'org.n52.wps.io.modules.parser.SimpleGMLParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://geoserver.itc.nl:8080/wps/schemas/gml/2.1.2/gmlpacket.xsd', '', 'org.n52.wps.io.modules.parser.SimpleGMLParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/gmlpacket.xsd', '', 'org.n52.wps.io.modules.parser.SimpleGMLParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.0.0', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.1', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2.1', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.parser.GML2BasicParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/image-ascii-grass', '', '', 'org.n52.wps.io.modules.parser.AsciiGrassParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.parser.GTBinZippedSHPParserCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.parser.GTBinZippedSHPParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/vnd.google-earth.kml+xml', 'http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd', '', 'org.n52.wps.io.modules.parser.GRASSKMLParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/vnd.google-earth.kml+xml', 'http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd', '', 'org.n52.wps.io.modules.parser.KMLParserCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-wkt', '', 'Base64', 'org.n52.wps.io.modules.parser.GTBinZippedWKT64ParserCM', TRUE);


INSERT INTO FORMATENTRY VALUES('application/x-jsongeometry', '', 'UTF-8', 'org.n52.wps.io.modules.generator.JSONGeometryGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.0', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.1', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.0', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.1', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.2.1', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML3BasicGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.0.0', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.1', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2.1', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GML2BasicGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://www.opengeospatial.org/gmlpacket.xsd', '', 'org.n52.wps.io.modules.generator.SimpleGMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://geoserver.itc.nl:8080/wps/schemas/gml/2.1.2/gmlpacket.xsd', '', 'org.n52.wps.io.modules.generator.SimpleGMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/gmlpacket.xsd', '', 'org.n52.wps.io.modules.generator.SimpleGMLGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/image-ascii-grass', '', '', 'org.n52.wps.io.modules.generator.AsciiGrassGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/image-ascii-grass', '', 'base64', 'org.n52.wps.io.modules.generator.AsciiGrassGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('image/tiff', '', 'base64', 'org.n52.wps.io.modules.generator.GeotiffGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/geotiff', '', 'base64', 'org.n52.wps.io.modules.generator.GeotiffGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('image/tiff', '', '', 'org.n52.wps.io.modules.generator.GeotiffGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('image/geotiff', '', '', 'org.n52.wps.io.modules.generator.GeotiffGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', 'base64', 'org.n52.wps.io.modules.generator.GTBinZippedSHPGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', '', 'base64', 'org.n52.wps.io.modules.generator.GTBinZippedSHPGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/x-zipped-shp', '', '', 'org.n52.wps.io.modules.generator.GTBinZippedSHPGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', '', '', 'org.n52.wps.io.modules.generator.GTBinZippedSHPGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.1/base/gml.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.0.0', 'http://schemas.opengis.net/gml/2.0.0/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.1', 'http://schemas.opengis.net/gml/2.1.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2', 'http://schemas.opengis.net/gml/2.1.2/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/2.1.2.1', 'http://schemas.opengis.net/gml/2.1.2.1/feature.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);
INSERT INTO FORMATENTRY VALUES('application/vnd.google-earth.kml+xml', 'http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd', '', 'org.n52.wps.io.modules.generator.GRASSXMLGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://www.opengeospatial.org/gmlpacket.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://geoserver.itc.nl:8080/wps/schemas/gml/2.1.2/gmlpacket.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml', 'http://schemas.opengis.net/gml/2.1.2/gmlpacket.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.0', 'http://schemas.opengis.net/gml/3.0.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.0.1', 'http://schemas.opengis.net/gml/3.0.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.0', 'http://schemas.opengis.net/gml/3.1.0/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.1.1', 'http://schemas.opengis.net/gml/3.1.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);
INSERT INTO FORMATENTRY VALUES('text/xml; subtype=gml/3.2.1', 'http://schemas.opengis.net/gml/3.2.1/base/feature.xsd', '', 'org.n52.wps.io.modules.generator.ProxyGMLGenerator4FilesCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/WMS', '', '', 'org.n52.wps.io.modules.generator.GeoserverWMSGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/WFS', '', '', 'org.n52.wps.io.modules.generator.GeoserverWFSGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/WCS', '', '', 'org.n52.wps.io.modules.generator.GeoserverWCSGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/WMS', '', '', 'org.n52.wps.io.modules.generator.MapserverWMSGeneratorCM', TRUE);

INSERT INTO FORMATENTRY VALUES('application/vnd.google-earth.kml+xml', 'http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd', '', 'org.n52.wps.io.modules.generator.KMLGeneratorCM', TRUE);

DELETE FROM CONFIGURATIONMODULE WHERE MODULE_CLASS_NAME='org.n52.wps.server.database.PostgresDatabaseConfigurationModule';
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.server.database.PostgresDatabaseConfigurationModule',FALSE);
INSERT INTO CONFIGURATIONMODULE VALUES('org.n52.wps.webapp.entities.Server',TRUE);
INSERT INTO CONFIGURATIONENTRY VALUES('hostport','org.n52.wps.webapp.entities.Server','8080');